# Site settings
title: Taskcluster In Action
email: pmoore@mozilla.com
description: > # this means to ignore newlines until "baseurl:"
  Multi-platform in-tree defined CI, against arbitrary systems or system
  images, containerised, dynamically generatable task topology, with integration
  to popular vcs providers such as GitHub.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://petemoore.github.io" # the base hostname & protocol for your site
github_username:  petemoore

# Build settings
markdown: kramdown

kramdown:
  input: GFM

# highlighter: pygments
